### ISSUE TITLE
[Feature Request] [Pending Discussion] Separate the data storage of different Tabs

### ISSUE THREAD

**Issue by ColaLinN** [RiverTwilight/Timeline#3]
**Separate the data storage of different Tabs**
Currently, the search, clear, and the limit of history amount impact both of History and Favorite because they are using the same `tweets` storage.
Ppl may not want to Garbage Collect their Favorite while the number of history has exceeded limit (100 as default). 
In this case, it is better to keep the data storage of different tabs separate.

**Comment by rivertwilight** [comment]
Thanks. This feature is now available.

**Comment by ColaLinN** [comment]
@RiverTwilight Thanks for the updates, respect
