### ISSUE TITLE
[Bug] Some posts are skipped. Posts with pure photos are not collected.

### ISSUE THREAD

**Issue by ColaLinN** [RiverTwilight/Timeline#4]
# Some posts are skipped.

![image](https://github.com/RiverTwilight/Timeline/assets/41199987/9194f17e-e3c6-4a8b-87e1-888df5578cf1)

# Posts with pure photos are not collected.

![image](https://github.com/RiverTwilight/Timeline/assets/41199987/da76bf08-c5c8-461b-8a86-b046c2decdeb)

**Comment by ColaLinN** [comment]
The above sample for Skipped posts is in a thread. 
Here is the sample 2 about it in the `Follow` stream.
![image](https://github.com/RiverTwilight/Timeline/assets/41199987/b8d2d037-e33e-4c1a-914a-b226d195269f)

**Comment by ColaLinN** [comment]
Seems the probability of these problems decreases in the new PR [Collect the parent host #1](https://github.com/RiverTwilight/Timeline/pull/1) because I add `setInterval(processTweets, 500);` to periodically process the Tweets.
>it might introduce new problems such as race conditions with other processTweets() call.

**Comment by ColaLinN** [comment]
I suspected this problem is caused by race conditions(i.e. the later post covers the prior) of the `chrome.storage.local.get` and `chrome.storage.local.set` used in saveTweet() are asynchronous. Probably needs to have lock or something to ensure the whole saveTweet operation is atomic.
![image](https://github.com/RiverTwilight/Timeline/assets/41199987/6fde908f-8515-41ac-a00c-558cdfe9f8e6)

**Comment by rivertwilight** [comment]
Sorry for the late response. I didn't receive the notification from GitHub about your issue! 🙏

I'll soon investigate these problems and your PR. :-)

**Comment by rivertwilight** [comment]
This should be fixed now. The latest release is under review by Google. Thanks for your feedback.

**Comment by ColaLinN** [comment]
As it is not urgent, no worries at all. 

Thanks for the update!
